version: '3'
services:
  web:
    build: .

    ports:
      - "3000:3000"
    dns: "8.8.8.8"
    volumes:
      - ".:/app"
    env_file: .env
    links:
      - db:db
      - solr:solr
      # In production instead add external_links for db
    command: bash -c "bin/rake assets:precompile && bin/rake db:create && bin/rake db:migrate && bin/rails s"

  # In production remove this and add an external link in web
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - ./database:/var/lib/postgresql
  solr:
    image: solr:7.0.1
    ports:
      - "8983:8983"
    volumes:
      - data:/opt/solr/server/solr/mycores
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - mycore
    links:
      - db:db
volumes:
  data: {}
