version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    dns: "8.8.8.8"
    volumes:
      - ".:/app"
    env_file: .env
    links:
      - db:db
      - redis:redis
      # In production instead add external_links for db
    command: bash -c "bundle exec rake assets:precompile && bundle exec rake db:setup && bundle exec rake db:migrate && bundle exec rails s"
  worker:
    build: .
    env_file: .env
    links:
      - db:db
      - redis:redis
    volumes:
      - ".:/app"
    command: bash -c "bundle exec sidekiq -q default -q mailers"
  # In production remove this and add an external link in web
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - ./database:/var/lib/postgresql

  redis:
    image: redis:latest
volumes:
  data: {}
